name: rolffz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59692
title: Rolff - current events
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
