title: Rolff - current events
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#4B4B4B'
    - '#282620'
    - '#FFFFF3'
    - '#BD9B77'
    - '#E0BD91'
  rhythmicContrast: 0.1941457
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: rolffz
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1487455
layout_spectrum: 0
