name: rolffz
favicon: null
layout_spectrum: 0.11275166575796902
typography_spectrum: 0.42929748399183154
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4617039645090699
  lightness: 0.7718315895181149
  saturation: 0.5968414021190256
  rhythmicContrast: 0.1313730925321579
purpose: []
